config/routes.rb
Rails.application.routes.draw do
  #Admins
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #Users
  devise_for :users
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
      resources :batches, only: [:index, :show] do
        get :join, on: :member
      end
    end
  end
  
  resources :batches, only: :show do
    get :join, on: :member
  end
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :manage, ActiveAdmin::Page, name: "Dashboard", namespace_name: "admin"
      can :manage, Course
      can :manage, Batch
      can :manage, StudentBatch
      can :manage, Student, school_id: user.schools
      can [:update, :read], School, created_by_admin_user_id: user.id
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  rolify
  resourcify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :roles, join_table: :admin_users_roles
  has_many :schools, foreign_key: :created_by_admin_user_id
  has_many :courses, through: :schools, class_name: 'Course', foreign_key: :school_id
  has_many :batches, through: :courses, class_name: 'Batch', foreign_key: :course_id
  has_many :students, through: :batches, class_name: 'User', foreign_key: :user_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :school, optional: true
  belongs_to :admin_user, optional: true, foreign_key: :course_id
  has_many :student_batches, foreign_key: :batch_id
  has_many :students, through: :student_batches, source: :user

  validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :school, optional: true
  belongs_to :admin_user, optional: true, foreign_key: :school_id
  has_many :batches

  validates :name, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :admin_users, join_table: :admin_users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, presence: true
end

app/models/school.rb
class School < ApplicationRecord
  validates :name, presence: true
  has_many :users
  has_many :courses
  has_many :batches
  belongs_to :admin_user, class_name: 'AdminUser', optional: true, foreign_key: :created_by_admin_user_id, primary_key: :id
end

app/models/student.rb
class Student < User
  belongs_to :school, optional: true
  has_many :student_batches, foreign_key: :user_id
  has_many :batches, through: :student_batches, class_name: 'StudentBatch'

  validates :school_id, presence: true
end

app/models/student_batch.rb
class StudentBatch < ApplicationRecord
  enum :status, [ :pending, :requested, :approved, :rejected ]

  belongs_to :user
  belongs_to :student, foreign_key: 'user_id', optional: true, class_name: 'User'
  belongs_to :batch

  validates :user_id, uniqueness: { scope: :batch_id }

  def self.get_status(batch_id, student_id)
    student_batch = find_by(batch_id: batch_id, user_id: student_id)
    student_batch&.status
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :rememberable
  include DeviseTokenAuth::Concerns::User

  validates :name, presence: true
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  include DeviseTokenAuth::Concerns::SetUserByToken
end

app/controllers/api/v1/batches_controller.rb
class Api::V1::BatchesController < Api::V1::ApiController
  before_action :authenticate_user!
  before_action :set_batch, only: [:show, :join]
  
  def index
    @batches = Batch.all
    render json: @batches
  end

  def show
    render json: @batch
  end

  def join
    student_batch = StudentBatch.new(batch_id: @batch.id, user_id: current_user.id, status: 1)
    if student_batch.save
      render json: { message: 'Join request sent please wait for school confirmation' }
    else
      render json: { error: student_batch.errors.full_messages.join(',') }
    end
  end

  private
  def set_batch
    @batch = Batch.find_by(id: params[:id])
    unless @batch
      render json: { error: 'Batch not found' }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: -> {params[:controller].split('/')[0] == 'devise_token_auth'}
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    redirect_to new_admin_user_session_path, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    if [Student, User].include?(resource.class)
      return dashboard_path
    end
    super
	end

  def after_sign_up_path_for(resource)
    if [Student, User].include?(resource.class)
      return new_user_session_path
    end
    super
  end

  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :name, :school_id])
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch

  def show
  end

  def join
    student_batch = StudentBatch.new(batch_id: @batch.id, user_id: current_user.id, status: 1)
    if student_batch.save
      flash[:notice] = 'Join request sent please wait for school confirmation'
    else
      flash[:alert] = 'Something went wrong. Try again later'
    end
    redirect_to dashboard_path
  end

  private
  def set_batch
    @batch = Batch.find(params[:id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @school = current_user.school
    @batches = @school.batches
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def format_status(batch, user_id)
    student_batch = batch.student_batches.find_by(batch_id: batch.id, user_id: user_id)
    student_batch&.status
  end
end

app/views/batches/show.html.erb
<h3>Welcome to School <%= current_user.name %> !!!</h3>
<div class='row'>
  <div class='col-sm-10'>
    <strong>Batch:</strong>&nbsp;<%= @batch.name %>
  </div>
  <div class='col-sm-2'>
    <%= link_to 'Back to Dashboard', dashboard_path %>
  </div>
</div>
<div class='row'>
  <div class='col-sm-12'>
    <strong>Students:</strong>
  </div>
  <div class='col-sm-12'>
    <table class='table table-bordered'>
      <thead>
        <tr>
          <th>Student ID</th>
          <th>Student Name</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @batch.students.each do |student| %>
          <tr class="<%= student.id == current_user.id ? 'table-info' : '' %>">
            <td><%= student.id %></td>
            <td><%= student.name %></td>
            <td><%= StudentBatch.get_status(@batch.id, student.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/show.html.erb
<h3>Welcome to School <%= current_user.name %> !!!</h3>
<div class='row'>
  <div class='col-sm-12'>
    <strong>School: <%= @school.name %></strong>
  </div>
  <div class='col-sm-12'>
    <strong>Batches:</strong>
  </div>
  <div class='col-sm-12'>
    <table class='table table-bordered'>
      <thead>
        <tr>
          <th>Batch Name</th>
          <th>School</th>
          <th>Student count</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @batches.each do |batch| %>
          <tr>
            <td>
              <% if format_status(batch, current_user.id) == 'approved' %>
                <%= link_to batch.name, batch_path(batch.id) %>
              <% else %>
                <%= batch.name %>
              <% end %>
            </td>
            <td><%= batch.school&.name %></td>
            <td><%= batch.students.count %></td>
            <td class="link <%= batch.name %>">
              <% if batch.students.include? current_user  %>
                <%= format_status(batch, current_user.id) %>
              <% else %>
                <%= link_to 'Join', join_batch_path(batch.id) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
Welcome To School

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolApp</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
      <a class='navbar-brand' href='#'>Emeritus School</a>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
        <span class='navbar-toggler-icon'></span>
      </button>
      <div class='collapse navbar-collapse' id='navbarNav'>
        <ul class='navbar-nav'>
          <% if user_signed_in? %>
            <li class='nav-item active'>
               <%= link_to 'Dashboard', dashboard_path, class: 'navbar-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
            </li>
          <% else %>
            <li class='nav-item active'>
              <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link'  %>
            </li>
            <li class='nav-item'>
              <%= link_to 'Login', new_user_session_path, class: 'navbar-link'  %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class='container'>
      <% if notice.present? %>
        <p class='alert alert-success'><%= notice %></p>
      <% elsif alert.present? %>
        <p class='alert alert-alert'><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>